//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace View_PBL4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileDetail
    {
        public string FileID { get; set; }
        public string Link { get; set; }
        public string Time { get; set; }
        public string FolderID { get; set; }
    
        public virtual Folder Folder { get; set; }
    }
}
